#!/usr/bin/env python3
"""
match_reports.py
================
Pipeline position: STEP 3 of 4
Depends on: download_data.py (./brats_data/ must exist)
Run after: run_inference.py   Run before: evaluate.py

Reference source (updated)
──────────────────────────
Uses "Predicted Report (gpt-oss:120b)" from the local btreport_brats23.json
as the reference for evaluation. This is a GPT-oss 120B report generated by
KurtLab from the actual BraTS segmentation-derived VASARI features and midline
shift measurements — the best available synthetic reference for BraTS patients.

Why not DeepSeek R1 1.5B (the previous source)?
  The old source was a tiny 6-patient file generated by a 1.5B model, producing
  garbled output with hallucinated terminology. The 120B model produces clean,
  structured reports grounded in the same metadata, covering all 1,251 patients.

Why not real clinical reports?
  BraTS-2023 is an imaging challenge — no public clinical radiology reports
  exist for these patients. All available references are LLM-generated from
  segmentation-derived metadata. The 120B model is the highest quality option.

btreport_brats23.json structure (local file, all 1,251 patients):
  {
    "BraTS-GLI-XXXXX-000": {
      "Predicted Report (gpt-oss:120b)": "FINDINGS\n...",
      "Predicted Report (llama3:70b)":   "FINDINGS\n..."
    }
  }

Also saves VASARI metadata for patients where it's available (fetched from
the small example_reports file which covers 6 patients). The metadata enables
factual verification in verify_metadata.py, which is more meaningful than
text-similarity metrics alone.

Output:
  ./reference_reports/<patient_id>.txt   — gpt-oss:120b text reference
  ./metadata/vasari_<patient_id>.json    — structured VASARI facts (when available)

Requirements: requests
"""

import json
import sys
from pathlib import Path

import requests

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# Local btreport_brats23.json — contains gpt-oss:120b reports for 1,251 patients
BTREPORT_LOCAL   = Path("./btreport_brats23.json")
REFERENCE_KEY    = "Predicted Report (gpt-oss:120b)"

# Small example file (6 patients) from BTReport GitHub — has VASARI metadata
METADATA_URL = (
    "https://raw.githubusercontent.com/KurtLabUW/BTReport/main/"
    "btreport/llm_report_generation/example_reports/"
    "brats23_metadata-report-deepseek-r1%3A1.5b.json"
)

BRATS_DIR    = Path("./brats_data")
REF_DIR      = Path("./reference_reports")
METADATA_DIR = Path("./metadata")


# ---------------------------------------------------------------------------
# Step 1 – Load the local btreport_brats23.json (gpt-oss:120b reports)
# ---------------------------------------------------------------------------

def load_local_btreport() -> dict:
    if not BTREPORT_LOCAL.exists():
        sys.exit(
            f"ERROR: {BTREPORT_LOCAL} not found.\n"
            f"Download it from: https://github.com/KurtLabUW/BTReport"
        )
    print(f"Loading {BTREPORT_LOCAL} …")
    with open(BTREPORT_LOCAL, encoding="utf-8") as f:
        data = json.load(f)
    print(f"  {len(data)} patients in btreport_brats23.json")
    return data


# ---------------------------------------------------------------------------
# Step 2 – Fetch VASARI metadata for patients that have it (6-patient file)
# ---------------------------------------------------------------------------

def fetch_vasari_metadata() -> dict:
    """
    Fetch the small example file that contains full VASARI + midline shift
    metadata for up to 6 patients. Save each patient's metadata as a JSON
    file under ./metadata/ for use by verify_metadata.py.
    Returns a dict keyed by patient ID.
    """
    print(f"\nFetching VASARI metadata from BTReport GitHub …")
    try:
        resp = requests.get(METADATA_URL, timeout=30)
        resp.raise_for_status()
        raw = resp.json()
    except Exception as e:
        print(f"  ⚠ Could not fetch VASARI metadata: {e}")
        print("  Continuing without metadata — factual verification will be unavailable.")
        return {}

    METADATA_DIR.mkdir(exist_ok=True)
    saved = []
    for pid, entry in raw.items():
        if "metadata" not in entry:
            continue
        out = METADATA_DIR / f"vasari_{pid}.json"
        with open(out, "w", encoding="utf-8") as f:
            json.dump(entry["metadata"], f, indent=2)
        saved.append(pid)

    print(f"  VASARI metadata saved for: {saved}")
    return {pid: raw[pid].get("metadata", {}) for pid in raw}


# ---------------------------------------------------------------------------
# Step 3 – Discover local BraTS patient IDs
# ---------------------------------------------------------------------------

def get_local_patient_ids() -> list[str]:
    if not BRATS_DIR.exists():
        sys.exit(f"ERROR: {BRATS_DIR} does not exist. Run download_data.py first.")
    ids = sorted(
        d.name for d in BRATS_DIR.iterdir()
        if d.is_dir() and d.name.startswith("BraTS-")
    )
    if not ids:
        sys.exit(f"ERROR: No BraTS patient directories found in {BRATS_DIR}.")
    print(f"\nLocal BraTS patients ({len(ids)}): {ids}")
    return ids


# ---------------------------------------------------------------------------
# Step 4 – Save gpt-oss:120b reports as reference
# ---------------------------------------------------------------------------

def save_reference_reports(btreport_data: dict, patient_ids: list[str]) -> None:
    """
    For each local patient ID, extract "Predicted Report (gpt-oss:120b)" from
    btreport_brats23.json and save it as the reference report.
    """
    REF_DIR.mkdir(parents=True, exist_ok=True)
    matched, unmatched = 0, 0

    for pid in patient_ids:
        ref_path = REF_DIR / f"{pid}.txt"

        if ref_path.exists():
            print(f"  {pid}  → already exists, skipping.")
            matched += 1
            continue

        if pid not in btreport_data:
            print(f"  {pid}  → NOT FOUND in btreport_brats23.json.")
            unmatched += 1
            continue

        report = btreport_data[pid].get(REFERENCE_KEY, "").strip()
        if not report:
            print(f"  {pid}  → '{REFERENCE_KEY}' field is empty.")
            unmatched += 1
            continue

        header = (
            f"# REFERENCE REPORT\n"
            f"# Patient ID : {pid}\n"
            f"# Source     : BTReport / gpt-oss:120b (VASARI-metadata-grounded)\n"
            f"# Key        : {REFERENCE_KEY}\n"
            f"{'#' * 72}\n\n"
        )
        ref_path.write_text(header + report, encoding="utf-8")
        print(f"  {pid}  → saved ({len(report)} chars)")
        matched += 1

    print(f"\nDone. {matched}/{len(patient_ids)} reference reports saved to {REF_DIR}/")
    if unmatched:
        print(f"WARNING: {unmatched} patient(s) had no reference in btreport_brats23.json.")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    btreport_data = load_local_btreport()
    fetch_vasari_metadata()          # saves VASARI JSONs; non-fatal if it fails
    patient_ids = get_local_patient_ids()
    save_reference_reports(btreport_data, patient_ids)

    saved = sorted(REF_DIR.glob("*.txt")) if REF_DIR.exists() else []
    print(f"\nReference reports in {REF_DIR}/:")
    for f in saved:
        print(f"  {f.name}")


if __name__ == "__main__":
    main()
